In [8]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

df = pd.read_csv('/home/lolkek3310/python/Подготовка Гомель/Аномалии/ Stroke Prediction Dataset/healthcare-dataset-stroke-data.csv')

df = df.drop('id', axis =1)

print(df.isnull().sum())

df['bmi'] = df['bmi'].fillna(df['bmi'].median())
df

gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  201
smoking_status         0
stroke                 0
dtype: int64

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,28.1,never smoked,1
2,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1
...,...,...,...,...,...,...,...,...,...,...,...
5105,Female,80.0,1,0,Yes,Private,Urban,83.75,28.1,never smoked,0
5106,Female,81.0,0,0,Yes,Self-employed,Urban,125.20,40.0,never smoked,0
5107,Female,35.0,0,0,Yes,Self-employed,Rural,82.99,30.6,never smoked,0
5108,Male,51.0,0,0,Yes,Private,Rural,166.29,25.6,formerly smoked,0
5109,Female,44.0,0,0,Yes,Govt_job,Urban,85.28,26.2,Unknown,0

In [9]:
df = pd.get_dummies(df, drop_first=True)
df

,age,hypertension,heart_disease,avg_glucose_level,bmi,stroke,gender_Male,gender_Other,ever_married_Yes,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,Residence_type_Urban,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes
0,67.0,0,1,228.69,36.6,1,True,False,True,False,True,False,False,True,True,False,False
1,61.0,0,0,202.21,28.1,1,False,False,True,False,False,True,False,False,False,True,False
2,80.0,0,1,105.92,32.5,1,True,False,True,False,True,False,False,False,False,True,False
3,49.0,0,0,171.23,34.4,1,False,False,True,False,True,False,False,True,False,False,True
4,79.0,1,0,174.12,24.0,1,False,False,True,False,False,True,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5105,80.0,1,0,83.75,28.1,0,False,False,True,False,True,False,False,True,False,True,False
5106,81.0,0,0,125.20,40.0,0,False,False,True,False,False,True,False,True,False,True,False
5107,35.0,0,0,82.99,30.6,0,False,False,True,False,False,True,False,False,False,True,False
5108,51.0,0,0,166.29,25.6,0,True,False,True,False,True,False,False,False,True,False,False
5109,44.0,0,0,85.28,26.2,0,False,False,True,False,False,False,False,True,False,False,False

In [10]:
X = df.drop('stroke', axis=1) 
y = df['stroke']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42,stratify=y)

model =RandomForestClassifier(n_estimators=100, class_weight='balanced', random_state=42)

model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Confusion Matrix:
[[971   1]
 [ 50   0]]

Classification Report:
              precision    recall  f1-score   support

           0       0.95      1.00      0.97       972
           1       0.00      0.00      0.00        50

    accuracy                           0.95      1022
   macro avg       0.48      0.50      0.49      1022
weighted avg       0.90      0.95      0.93      1022

In [ ]:
# Вместо простого predict, мы берем вероятность для каждого пациента
# y_probs будет содержать вероятности: [шанс здорового, шанс инсульта]
y_probs = model.predict_proba(X_test)[:, 1]

# Устанавливаем свой порог (Threshold). Например, 0.15 (15%)
# Если шанс инсульта > 15%, мы помечаем это как риск (1)
threshold = 0.15
y_pred_new = (y_probs > threshold).astype(int)

# Теперь смотрим результаты снова
print(f"--- Результаты с порогом {threshold} ---")
print(confusion_matrix(y_test, y_pred_new))
print(classification_report(y_test, y_pred_new))

--- Результаты с порогом 0.15 ---
[[902  70]
 [ 36  14]]
              precision    recall  f1-score   support

           0       0.96      0.93      0.94       972
           1       0.17      0.28      0.21        50

    accuracy                           0.90      1022
   macro avg       0.56      0.60      0.58      1022
weighted avg       0.92      0.90      0.91      1022

Logistic Regression (простая база).

Random Forest (то, что сделал ты).

XGBoost или LGBM (экстремальный градиентный бустинг — это современные «монстры», которые выигрывают почти все соревнования на Kaggle).